app/routes.php
<?php


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', 'HomeController@index');
Route::get('login', ['before' => 'guest', 'uses' => 'HomeController@login']);
Route::post('login', ['before' => 'guest', 'uses' => 'HomeController@makelogin']);
Route::get('logout', ['before' => 'auth', 'as' => 'logout', 'uses' => 'HomeController@logout']);
Route::get('reports', ['as' => 'reports', 'uses' => 'ReportController@index']);
Route::get('video', ['as' => 'video', 'uses' => 'VideoController@index']);
Route::get('poster', ['as' => 'poster', 'uses' => 'PosterController@index']);
Route::resource('event', 'EventController', ['only' => ['index', 'show']]);
Route::resource('page', 'PageController', ['only' => ['show']]);
Route::resource('gallery', 'GalleryController', ['only' => ['index', 'show']]);
Route::get('archive', ['as' => 'archive', 'uses' => 'ArchiveController@index']);

//routes for admin panel
Route::group(['before' => 'auth', 'prefix' => 'admin', 'namespace' => 'Admin'], function () {
    Route::get('/', 'EventController@index');
    Route::resource('event', 'EventController', ['except' => ['show']]);
    Route::resource('page', 'PageController', ['except' => ['show']]);
    Route::resource('gallery', 'GalleryController', ['except' => 'show']);
    Route::resource('gallery.photo', 'GalleryPhotoController', ['only' => ['store', 'destroy', 'index']]);
    Route::resource('video', 'VideoController', ['only' => ['index', 'store', 'destroy']]);
    Route::resource('report', 'ReportController');
    Route::resource('url', 'UrlController', ['except' => 'create']);
    Route::resource('banner', 'BannerController');
    Route::get('user', ['as' => 'admin.user.index', 'uses' => 'UserController@index']);
    Route::post('user', ['as' => 'admin.user.update', 'uses' => 'UserController@update']);
});

//routes for elfinder
Route::group(array('before' => 'auth'), function() {
  Route::get('elfinder', 'Barryvdh\Elfinder\ElfinderController@showIndex');
  Route::any('elfinder/connector', 'Barryvdh\Elfinder\ElfinderController@showConnector');
  Route::get('elfinder/ckeditor4', 'Barryvdh\Elfinder\ElfinderController@showCKeditor4');
});  

app/views/admin/page/create.blade.php
@extends('layout.admin')

@section('content')
  @foreach($errors->all() as $error)
    <div class="alert-danger alert">{{ $error }}</div>
  @endforeach
  <legend><h2>Добавить страницу</h2></legend>
  <form class="form-horizontal" action="{{{ route("admin.page.store") }}}" method="POST" enctype="multipart/form-data">
    <div class="form-group">
      <div class="col-lg-3">
        <label class="control-label">Название</label>
      </div>
      <div class="col-lg-4">
        <input type="text" class="form-control" name="title" value="{{{ Input::old('title') }}}">
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-3">
        <label class="control-label">Адрес страницы на латинице</label>
      </div>
      <div class="col-lg-4">
        <input type="text" class="form-control" name="url" value="{{{ Input::old('url') }}}">
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-3">
        <label class="control-label">
          Содержание
        </label>
      </div>
      <div class="col-lg-9">
        <textarea id="add-page-textarea" name="content">{{ Input::old('content') }}</textarea>
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-3">
        <label class="control-label">
          Дополнительный HTML-код
        </label>
      </div>
      <div class="col-lg-9">
        <textarea name="additional-html" class="form-control">{{ Input::old('additional-html') }}</textarea>
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-4 col-lg-offset-3">
        <button class="btn btn-default" type="submit">Создать</button>
      </div>
    </div>
  </form>
@stop

app/views/admin/page/edit.blade.php
@extends('layout.admin')

@section('content')
  @foreach($errors->all() as $error)
    <div class="alert-danger alert">{{ $error }}</div>
  @endforeach
  <legend><h2>Редактировать страницу</h2></legend>
  <form class="form-horizontal" action="{{{ route("admin.page.update", array("page" => $page->id)) }}}" method="POST" enctype="multipart/form-data">
    <div class="form-group">
      <div class="col-lg-3">
        <label class="control-label">Название</label>
      </div>
      <div class="col-lg-4">
        <input type="text" class="form-control" name="title" value="{{{ $page->title }}}">
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-3">
        <label class="control-label">Адрес страницы на латинице</label>
      </div>
      <div class="col-lg-4">
        <input type="text" class="form-control" name="url" value="{{{ $page->url }}}">
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-3">
        <label class="control-label">
          Содержание
        </label>
      </div>
      <div class="col-lg-9">
        <textarea id="add-page-textarea" name="content">{{ $page->content }}</textarea>
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-3">
        <label class="control-label">
          Дополнительный HTML-код
        </label>
      </div>
      <div class="col-lg-9">
        <textarea name="additional-html" class="form-control">{{ $page->additional_html }}</textarea>
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-4 col-lg-offset-3">
        <button class="btn btn-default" type="submit">Сохранить</button>
      </div>
    </div>
    <input type="hidden" name="_method" value="put">
  </form>
@stop

app/views/admin/page/index.blade.php
@extends('layout.admin')

@section('content')
  <a href="{{{ route('admin.page.create') }}}" class="btn btn-default">Создать страницу</a>
  <table class="table" style="margin-top: 10px;">
    <tr>
      <th>Заголовок</th>
      <th>Ссылка</th>
      <th>Дата создания</th>
      <th>Действия</th>
    </tr>
    @foreach ($pages as $page)
      <tr class="page" data-id="{{{ $page->id }}}">
        <td> {{{ $page->title }}} </td>
        <td> {{{ route('page.show', ['page' => $page->getIDForUrl()]) }}} </td>
        <td> {{{ $page->created_at->format('d.m.Y H:i:s') }}} </td>
        <td>
          <a class="btn btn-default" href="{{{ route('admin.page.edit', ['page' => $page->id]) }}}">Редактировать</a>
          <a class="btn btn-danger delete-page-button" href="{{{ route('admin.page.destroy', ['page' => $page->id]) }}}" data-id="{{{ $page->id }}}">Удалить</a>
        </td>
      </tr>
    @endforeach
  </table>
  {{ $pages->links() }}
@stop