app/routes.php
<?php


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', 'HomeController@index');
Route::get('login', ['before' => 'guest', 'uses' => 'HomeController@login']);
Route::post('login', ['before' => 'guest', 'uses' => 'HomeController@makelogin']);
Route::get('logout', ['before' => 'auth', 'as' => 'logout', 'uses' => 'HomeController@logout']);
Route::get('reports', ['as' => 'reports', 'uses' => 'ReportController@index']);
Route::get('video', ['as' => 'video', 'uses' => 'VideoController@index']);
Route::get('poster', ['as' => 'poster', 'uses' => 'PosterController@index']);
Route::resource('event', 'EventController', ['only' => ['index', 'show']]);
Route::resource('page', 'PageController', ['only' => ['show']]);
Route::resource('gallery', 'GalleryController', ['only' => ['index', 'show']]);
Route::get('archive', ['as' => 'archive', 'uses' => 'ArchiveController@index']);

//routes for admin panel
Route::group(['before' => 'auth', 'prefix' => 'admin', 'namespace' => 'Admin'], function () {
    Route::get('/', 'EventController@index');
    Route::resource('event', 'EventController', ['except' => ['show']]);
    Route::resource('page', 'PageController', ['except' => ['show']]);
    Route::resource('gallery', 'GalleryController', ['except' => 'show']);
    Route::resource('gallery.photo', 'GalleryPhotoController', ['only' => ['store', 'destroy', 'index']]);
    Route::resource('video', 'VideoController', ['only' => ['index', 'store', 'destroy']]);
    Route::resource('report', 'ReportController');
    Route::resource('url', 'UrlController', ['except' => 'create']);
    Route::resource('banner', 'BannerController');
    Route::get('user', ['as' => 'admin.user.index', 'uses' => 'UserController@index']);
    Route::post('user', ['as' => 'admin.user.update', 'uses' => 'UserController@update']);
});

//routes for elfinder
Route::group(array('before' => 'auth'), function() {
  Route::get('elfinder', 'Barryvdh\Elfinder\ElfinderController@showIndex');
  Route::any('elfinder/connector', 'Barryvdh\Elfinder\ElfinderController@showConnector');
  Route::get('elfinder/ckeditor4', 'Barryvdh\Elfinder\ElfinderController@showCKeditor4');
});  

app/models/Event.php
<?php

class Event extends BaseModel
{
    protected $table = 'events';
    
    protected $fillable = array("title", "description", "price", "time", "date");
    protected $guarded = array("id");

    protected $rules = array(
        "title" => "required",
        "description" => "required",
        "price" => "required",
        "time" => "required",
        "date" => "required|date",
        "icon" => "image",
        "main-photo" => "image",
    );

    public function photos()
    {
        return $this->hasMany('EventPhoto');
    }

    public function setDateAttribute($value)
    {
        $this->attributes['date'] = date("Y-m-d", strtotime($value));
    }


    public function getDay()
    {
        return $this->date->formatLocalized('%d');
    }

    public function getMonth()
    {
        return Lang::get("locale.month." . $this->date->formatLocalized('%B'));
    }

    public function saveSmallPhoto($photo)
    {
        $small_photos_path = "uploads" . DIRECTORY_SEPARATOR . "event_small_photos";
        $uuid = uniqid();
        while(File::exists(public_path() . DIRECTORY_SEPARATOR . $small_photos_path . DIRECTORY_SEPARATOR . $uuid))
            $uuid = uniqid();
        $small_photo_path = $small_photos_path . DIRECTORY_SEPARATOR . $uuid;
        $this->makeDirectory(public_path() . DIRECTORY_SEPARATOR . $small_photo_path);
        
        $filename = $photo->getClientOriginalName();
        
        $thumbnail = InterventionImage::make($photo)->fit(80, 80, function($constraint) {
            $constraint->upsize();
        });

        $thumbnail->save(public_path() . DIRECTORY_SEPARATOR . $small_photo_path . DIRECTORY_SEPARATOR . $filename);
        $this->icon = $small_photo_path . DIRECTORY_SEPARATOR . $filename;
    }

    public function saveMainPhoto($photo)
    {
        $main_photos_path = "uploads" . DIRECTORY_SEPARATOR . "event_main_photos";
        $uuid = uniqid();
        while(File::exists(public_path() . DIRECTORY_SEPARATOR . $main_photos_path . DIRECTORY_SEPARATOR . $uuid))
            $uuid = uniqid();
        $main_photo_path = $main_photos_path . DIRECTORY_SEPARATOR . $uuid;
        $this->makeDirectory($main_photo_path);
        
        $original_file_path = $main_photo_path . DIRECTORY_SEPARATOR . "original";
        $thumbnail_file_path = $main_photo_path . DIRECTORY_SEPARATOR . "thumbnail";
        $this->makeDirectory(public_path() . DIRECTORY_SEPARATOR . $original_file_path);
        $this->makeDirectory(public_path() . DIRECTORY_SEPARATOR . $thumbnail_file_path);
        
        $filename = $photo->getClientOriginalName();
        
        $original_file = $photo->move(public_path() . DIRECTORY_SEPARATOR . $original_file_path, $filename);
        
        $thumbnail = InterventionImage::make($original_file->getRealPath())->resize(700, null, function($constraint) {
            $constraint->upsize();
            $constraint->aspectRatio();
        });
        $thumbnail->save(public_path() . DIRECTORY_SEPARATOR . $thumbnail_file_path . DIRECTORY_SEPARATOR . $filename);
        $this->main_photo_thumbnail = $thumbnail_file_path . DIRECTORY_SEPARATOR . $filename;
        $this->main_photo = $original_file_path . DIRECTORY_SEPARATOR . $filename;
    }

    private function makeDirectory($path, $mode = 0777)
    {
        if(!File::exists($path))
            File::makeDirectory($path, $mode, true);
    }

    public function getDates()
    {
        return array('created_at', 'updated_at', 'date');
    }

    public function getDescriptionAsText()
    {
        return html_entity_decode(strip_tags($this->description));
    }
}

app/controllers/Admin/EventController.php
<?php

namespace Admin;

use \Event as Event;
use \View as View;
use \Input as Input;
use \Validator as Validator;

class EventController extends \BaseController {

    /**
     * Display a listing of the resource.
     *
     * @return Response
     */
    public function index()
    {
        $events = Event::orderBy('created_at', 'desc')->paginate(20);
        return View::make('admin.event.index')->with('events', $events);
    }


    /**
     * Show the form for creating a new resource.
     *
     * @return Response
     */
    public function create()
    {
        return View::make('admin.event.create');
    }
    

    /**
     * Store a newly created resource in storage.
     *
     * @return Response
     */
    public function store()
    {
        $input = Input::only("title", "description", "time", "date", "price");
        
        $event = new Event;
        
        //validate event
        if($event->validate($input)) {
            $event->date = Input::get("date");
            $event->title = Input::get("title");
            $event->description = Input::get("description");
            $event->price = Input::get("price");
            $event->time = Input::get("time");
            $event->type = Input::get("type");
            $image_rule = array("image" => "image");
            
            //validate and save small photo
            if(Input::hasFile("small-photo")) {
                $validator = Validator::make(array("image" => Input::file("small-photo")), $image_rule);
                if($validator->passes()) {
                    $event->saveSmallPhoto(Input::file("small-photo"));
                }
                else {
                    return View::make("admin.event.create")->withErrors($validator);
                }
            }
            
            //validate and save main-photo
            if(Input::hasFile("main-photo")) {
                $validator = Validator::make($image_rule, array("image" => Input::file("main-photo")));
                if($validator->passes()) {
                    $event->saveMainPhoto(Input::file("main-photo"));
                } else {
                    return View::make("admin.event.create")->withErrors($validator);
                }
            }

            $event->save();
            $events = Event::orderBy('created_at', 'desc')->paginate(20);
            return View::make('admin.event.index')->with("events", $events);
        }
        else {
            return View::make('admin.event.create')->withErrors($event->validator);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return Response
     */
    public function edit($id)
    {
        $event = Event::find($id);
        return View::make("admin.event.edit")->with("event", $event);
    }


    /**
     * Update the specified resource in storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function update($id)
    {   
        $event = Event::find($id);
        if(!$event) App::Abort(404);
        
        $input = Input::only("title", "description", "time", "date", "price");
        //validate event
        if($event->validate($input)) {
            $event->date = Input::get("date");
            $event->title = Input::get("title");
            $event->description = Input::get("description");
            $event->price = Input::get("price");
            $event->time = Input::get("time");
            $event->type = Input::get("type");
            $image_rule = array("image" => "image");
            
            //validate and save small photo
            if(Input::hasFile("small-photo")) {
                $validator = Validator::make(array("image" => Input::file("small-photo")), $image_rule);
                if($validator->passes()) {
                    $event->saveSmallPhoto(Input::file("small-photo"));
                }
                else {
                    return View::make("admin.event.edit")->with("event", $event)->withErrors($validator);
                }
            }
            
            //validate and save main-photo
            if(Input::hasFile("main-photo")) {
                $validator = Validator::make($image_rule, array("image" => Input::file("main-photo")));
                if($validator->passes()) {
                    $event->saveMainPhoto(Input::file("main-photo"));
                } else {
                    return View::make("admin.event.edit")->with("event", $event)->withErrors($validator);
                }
            }

            $event->save();
            $events = Event::orderBy('created_at', 'desc')->paginate(20);
            return View::make('admin.event.index')->with("events", $events);
        }
        else {
            return View::make('admin.event.edit')->with("event", $event)->withErrors($event->validator);
        }
    }


    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return Response
     */
    public function destroy($id)
    {
        Event::destroy($id);
        return \Response::json(array("status" => "ok"));
    }
}

app/controllers/EventController.php
<?php

class EventController extends \BaseController {
  
	/**
	 * Display the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function show($id)
	{
		$event = Event::find($id);
    if(!$event) App::abort(404);
    return View::make("event.show")->with("event", $event);
	}
}

app/views/admin/event/create.blade.php
@extends('layout.admin')

@section('content')
  @foreach($errors->all() as $error)
    <div class="alert-danger alert">{{ $error }}</div>
  @endforeach
  <legend><h2>Добавить событие</h2></legend>
  <form class="form-horizontal" action="{{{ route("admin.event.store") }}}" method="POST" enctype="multipart/form-data">
    <div class="form-group">
      <div class="col-lg-3">
        <label class="control-label">Название</label>
      </div>
      <div class="col-lg-4">
        <input type="text" class="form-control" name="title">
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-3">
        <label class="control-label">Дата</label>
      </div>
      <div class="col-lg-2">
        <input type="text" class="form-control" name="date" id="add-event-date-field">
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-3">
        <label class="control-label">Цена</label>
      </div>
      <div class="col-lg-2">
        <input type="text" class="form-control" name="price">
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-3">
        <label class="control-label">Время</label>
      </div>
      <div class="col-lg-2">
        <input type="text" class="form-control" name="time">
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-3">
        <label class="control-label">
          Описание
        </label>
      </div>
      <div class="col-lg-9">
        <textarea id="add-event-textarea" name="description"></textarea>
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-3">
        <label class="control-label">
          Тип события
        </label>
      </div>
      <div class="col-lg-2">
        <input type="text" name="type" class="form-control">
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-3">
        <label class="control-label">
          Фото 80x80 в заголовке
        </label>
      </div>
      <div class="col-lg-4">
        <input type="file" name="small-photo">
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-3">
        <label class="control-label">
          Главное фото
        </label>
      </div>
      <div class="col-lg-4">
        <input type="file" name="main-photo">
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-4 col-lg-offset-3">
        <button class="btn btn-default" type="submit">Создать</button>
      </div>
    </div>
  </form>
@stop

app/views/admin/event/edit.blade.php
@extends('layout.admin')

@section('content')
  @foreach($errors->all() as $error)
    <div class="alert-danger alert">{{ $error }}</div>
  @endforeach
  <legend><h2>Редактировать событие</h2></legend>
  <form class="form-horizontal" action="{{{ route("admin.event.update", array("event" => $event->id)) }}}" method="POST" enctype="multipart/form-data">
    <div class="form-group">
      <div class="col-lg-3">
        <label class="control-label">Название</label>
      </div>
      <div class="col-lg-4">
        <input type="text" class="form-control" name="title" value="{{{ $event->title }}}">
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-3">
        <label class="control-label">Дата</label>
      </div>
      <div class="col-lg-2">
        <input type="text" class="form-control" name="date" id="add-event-date-field" value="{{{ date("d.m.Y", strtotime($event->date)) }}}">
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-3">
        <label class="control-label">Цена</label>
      </div>
      <div class="col-lg-2">
        <input type="text" class="form-control" name="price" value="{{{ $event->price }}}">
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-3">
        <label class="control-label">Время</label>
      </div>
      <div class="col-lg-2">
        <input type="text" class="form-control" name="time" value="{{{ $event->time  }}}">
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-3">
        <label class="control-label">
          Описание
        </label>
      </div>
      <div class="col-lg-9">
        <textarea id="add-event-textarea" name="description">{{ $event->description }}</textarea>
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-3">
        <label class="control-label">
          Тип события
        </label>
      </div>
      <div class="col-lg-2">
        <input type="text" name="type" class="form-control" value="{{{ $event->type }}}">
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-3">
        <label class="control-label">
          Фото 80x80 в заголовке
        </label>
      </div>
      <div class="col-lg-4">
        <input type="file" name="small-photo">
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-3">
        <label class="control-label">
          Главное фото
        </label>
      </div>
      <div class="col-lg-4">
        <input type="file" name="main-photo">
      </div>
    </div>
    <div class="form-group">
      <div class="col-lg-4 col-lg-offset-3">
        <button class="btn btn-default" type="submit">Сохранить</button>
      </div>
    </div>
    <input type="hidden" name="_method" value="put">
  </form>
@stop

app/views/admin/event/index.blade.php
@extends('layout.admin')

@section('content')
  <div class="row">
    <div class="col-lg-2">
      <a class="btn btn-default" href="{{ route("admin.event.create")  }}">Добавить событие</a>
    </div>
  </div>
  <table class="table" style="margin-top: 10px;">
    <tr>
      <th>Дата</th>
      <th>Заголовок</th>
      <th>Дата создания</th>
      <th> Действия </th>
    </tr>
    @foreach($events as $event)
      <tr class="event" data-id="{{{ $event->id }}}">
        <td>{{{  $event->date->format("d.m.Y") }}} </td>
        <td>{{{ $event->title }}} </td>
        <td>{{{ $event->created_at->format("d.m.Y H:i:s")  }}}</td>
        <td>
          <a class="btn btn-default" href="{{{ route("admin.event.edit", array("event" => $event->id)) }}}">Редактировать</a>
          <a class="btn btn-danger delete-event-button" href="{{{ route("admin.event.destroy", array("event" => $event->id)) }}}" data-id="{{{ $event->id }}}">Удалить</a>
        </td>
      </tr>
    @endforeach
  </table>
  {{ $events->links() }}
@stop