app/routes.php
<?php


/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::get('/', 'HomeController@index');
Route::get('login', ['before' => 'guest', 'uses' => 'HomeController@login']);
Route::post('login', ['before' => 'guest', 'uses' => 'HomeController@makelogin']);
Route::get('logout', ['before' => 'auth', 'as' => 'logout', 'uses' => 'HomeController@logout']);
Route::get('reports', ['as' => 'reports', 'uses' => 'ReportController@index']);
Route::get('video', ['as' => 'video', 'uses' => 'VideoController@index']);
Route::get('poster', ['as' => 'poster', 'uses' => 'PosterController@index']);
Route::resource('event', 'EventController', ['only' => ['index', 'show']]);
Route::resource('page', 'PageController', ['only' => ['show']]);
Route::resource('gallery', 'GalleryController', ['only' => ['index', 'show']]);
Route::get('archive', ['as' => 'archive', 'uses' => 'ArchiveController@index']);

//routes for admin panel
Route::group(['before' => 'auth', 'prefix' => 'admin', 'namespace' => 'Admin'], function () {
    Route::get('/', 'EventController@index');
    Route::resource('event', 'EventController', ['except' => ['show']]);
    Route::resource('page', 'PageController', ['except' => ['show']]);
    Route::resource('gallery', 'GalleryController', ['except' => 'show']);
    Route::resource('gallery.photo', 'GalleryPhotoController', ['only' => ['store', 'destroy', 'index']]);
    Route::resource('video', 'VideoController', ['only' => ['index', 'store', 'destroy']]);
    Route::resource('report', 'ReportController');
    Route::resource('url', 'UrlController', ['except' => 'create']);
    Route::resource('banner', 'BannerController');
    Route::get('user', ['as' => 'admin.user.index', 'uses' => 'UserController@index']);
    Route::post('user', ['as' => 'admin.user.update', 'uses' => 'UserController@update']);
});

//routes for elfinder
Route::group(array('before' => 'auth'), function() {
  Route::get('elfinder', 'Barryvdh\Elfinder\ElfinderController@showIndex');
  Route::any('elfinder/connector', 'Barryvdh\Elfinder\ElfinderController@showConnector');
  Route::get('elfinder/ckeditor4', 'Barryvdh\Elfinder\ElfinderController@showCKeditor4');
});  

app/controllers/Admin/UrlController.php
<?php 

namespace Admin;
use \Input as Input;
use \UserURL as UserURL;
use \Response as Response;
use \View as View;
use \Config as Config;
use \Redirect as Redirect;

class UrlController extends \BaseController {

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$regions = Config::get('regions');
    $urls = $this->getURLs();
    
    return View::make('admin.url.index')->with('urls', $urls)->with('regions', $regions);
	}


	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		//
	}


	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$url = new UserURL;
    $input = Input::only('url', 'url_text');
    if($url->validate($input)) {
      $url->url = Input::get('url');
      $url->url_text = Input::get('url_text');
      $url->region = Input::get('_region');
      $url->order = UserURL::where('region', Input::get('_region'))->max('order') + 1;
      $url->save();
    }
    else {
      return View::make('admin.url.index')
        ->with('regions', Config::get('regions'))
        ->with('urls', $this->getURLs())
        ->withErrors($url->validator);
    }
    return Redirect::route('admin.url.index');
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
    $url = UserURL::find($id);
    $input = Input::only('url', 'url_text', 'order');
    if($url->validate($input)) {
      $url->url = Input::get('url');
      $url->url_text = Input::get('url_text');
      $url->order = Input::get('order');
      $url->save();
    }
    else {
      return View::make('admin.url.index')
        ->with('regions', Config::get('regions'))
        ->with('urls', $this->getURLs())
        ->withErrors($url->validator);
    }
    return Redirect::route('admin.url.index');
	}


	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		UserURL::destroy($id);
    
    return Response::json(["status" => "ok"]);
	}
  
  private function getURLs()
  {
    $urls = [];
    $regions = Config::get('regions');
    foreach($regions as $region) {
      $urls[$region] = UserURL::where('region', $region)->orderBy('order', 'asc')->get();
    }
    
    return $urls;
  }
}

app/views/admin/url/index.blade.php
@extends('layout.admin')

@section('content')
  @foreach($errors->all() as $error)
    <div class="alert-danger alert">{{ $error }}</div>
  @endforeach
  @foreach($regions as $region)
    <legend><h2>{{{ Lang::get('regions.' . $region) }}}</h2></legend>
    <table class="table">
      <tr>
        <th>Текст</th>
        <th>URL</th>
        <th>Дата создания</th>
        <th>Порядок</th>
        <th>Действия</th>
      </tr>
      @foreach($urls[$region] as $url)
        <tr class="url" data-id="{{{ $url->id }}}">
          <td>{{{ $url->url_text }}}</td>
          <td>{{{ $url->url }}}</td>
          <td>{{{ $url->created_at }}}</td>
          <td>{{{ $url->order }}}</td>
          <td>
            <button data-toggle="modal" data-target="#url-popup-{{{$url->id}}}" class="btn btn-default">
              Редактировать
            </button>
            <a href="{{{ route('admin.url.destroy', ['url' => $url->id]) }}}" data-id="{{{ $url->id }}}" class="btn btn-danger delete-url-button">
              Удалить
            </a>
          </td>
        </tr>
      @endforeach
    </table>
    <form class="form-horizontal" action="{{{ route('admin.url.store') }}}" method="POST">
      <div class="form-group">
        <div class="col-lg-1">
          <label class="control-label">URL</label>
        </div>
        <div class="col-lg-2">
          <input type="text" name="url" class="form-control">
        </div>
        <div class="col-lg-1">
          <label class="control-label">Текст</label>
        </div>
        <div class="col-lg-2">
          <input type="text" name="url_text" class="form-control">
        </div>
        <div class="col-lg-2">
          <button type="submit" class="btn btn-default">Добавить</button>
        </div>
      </div>
      <input type="hidden" name="_region" value="{{{ $region }}}">
    </form>
  @endforeach
  
  @foreach($regions as $region)
    @foreach($urls[$region] as $url)
      <div id="url-popup-{{{$url->id}}}" class="modal fade" aria-hidden="true">
          <div class="modal-dialog">
            <div class="modal-content">
              <form class="form-horizontal" action="{{{ route('admin.url.update', ['url' => $url->id]) }}}" method="POST">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Закрыть</span></button>
                  <h4 class="modal-title">Редактирование ссылки</h4>
                </div>
                <div class="modal-body">
                  <label class="control-label">URL</label>
                  <input type="text" name="url" class="form-control" value="{{{ $url->url }}}">
                  <label class="control-label">Текст</label>
                  <input type="text" name="url_text" class="form-control" value="{{{ $url->url_text }}}">
                  <label class="control-label">Порядок</label>
                  <input type="text" name="order" class="form-control" value="{{{ $url->order }}}">
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">Отмена</button>
                  <button type="submit" class="btn btn-primary">Сохранить</button>
                </div>
                <input type="hidden" name="_method" value="put">
              </form>
            </div><!-- /.modal-content -->
          </div><!-- /.modal-dialog -->
      </div><!-- /.modal -->
    @endforeach
  @endforeach
@stop